import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import DatePicker from "../components/DatePicker/Index";

const Home: NextPage = () => {
  const [items, setItems] = useState([1]);

  return (
    <div className="">
      <Head>
        <title>Product Expiry List | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        {/* <Monthpicker /> */}
        <DatePicker />
        {items.length > 0 ? "Atleast 1 item" : "Hurray!! No items"}
        <button className="">+</button>
      </main>
    </div>
  );
};

export default Home;
