import { useContext, useEffect, useState } from "react";
import { UserData } from "../context/Context";
import type { NextPage } from "next";
import Head from "next/head";
import DatePicker from "../components/DatePicker/Index";
import Container from "react-bootstrap/Container";
import Button from "react-bootstrap/Button";
import InputModal from "../components/InputModal";
import NoProductToShow from "../components/NoProductToShow";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import styles from "../styles/Home.module.css";
import ProductsContainer from "../components/ProductsContainer";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { items, userDetails } = useContext(UserData);
  const router = useRouter();

  const [show, setShow] = useState(false);
  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  useEffect(() => {
    if (!userDetails) {
      router.push("/signin");
    }
  }, []);

  return (
    <Container>
      <Head>
        <title>Product Expiry List | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="position-relative min-vh-100 py-3">
        <Row>
          <Col xs={12} md={6}>
            <DatePicker />
          </Col>
        </Row>
        <div
          className={`${styles.min_vh_80} d-flex justify-content-center flex-column`}
        >
          {items.length > 0 ? <ProductsContainer /> : <NoProductToShow />}
        </div>
        <Button
          variant="primary"
          onClick={handleShow}
          className="rounded-circle fs-2 py-1 px-3 position-absolute bottom-0 end-0 mr-3 mb-3"
        >
          +
        </Button>
        <InputModal show={show} handleClose={handleClose} />
      </main>
    </Container>
  );
};

export default Home;
