import type { NextPage } from 'next'
import Head from 'next/head'

const SignIn: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Product Expiry List | Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
      </main>
    </div>
  )
}

export default SignIn
